# Generated by Django 4.2.14 on 2024-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatar-icon.png", null=True, upload_to="images/"
            ),
        ),
    ]
