# Generated by Django 4.2.14 on 2024-07-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options_user_role_alter_user_username_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Follow",
            new_name="Subscribe",
        ),
        migrations.RenameField(
            model_name="subscribe",
            old_name="following",
            new_name="following_user",
        ),
    ]
