# Generated by Django 4.2.14 on 2024-08-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_is_subcribed_alter_subscribe_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_subcribed",
            new_name="is_subscribed",
        ),
    ]
