# Generated by Django 4.2.14 on 2024-09-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_is_subcribed_user_is_subscribed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("user", "пользователь"), ("admin", "администратор")],
                default="user",
                max_length=10,
                verbose_name="Роль",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscribe",
            constraint=models.CheckConstraint(
                check=models.Q(("user", models.F("following_user")), _negated=True),
                name="prevent_self_follow",
            ),
        ),
    ]
